# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuradores', '0009_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='EstadoBodega',
        ),
        migrations.DeleteModel(
            name='Frecuencia',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Referencia',
        ),
        migrations.DeleteModel(
            name='Responsable',
        ),
        migrations.DeleteModel(
            name='TipoBodega',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
        migrations.DeleteModel(
            name='TipoDetalleEntradaSalidad',
        ),
        migrations.DeleteModel(
            name='TipoMateriaPrima',
        ),
        migrations.DeleteModel(
            name='TipoProceso',
        ),
        migrations.DeleteModel(
            name='TipoResiduo',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
