# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 01:08
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enciclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='pagina',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='primaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resumen',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
